version: '3.4'

services:
  ordermicroservice:
    image: ${DOCKER_REGISTRY-}ordermicroservice
    build:
      context: .
      dockerfile: OrderMicroservice/Dockerfile
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - DB_CONNECTION_STRING=Server=192.168.1.28,1432;Database=OrderDB;User Id=sa;Password=Barisaltun508*;Trusted_Connection=False;MultipleActiveResultSets=true
     - API_URL=http://host.docker.internal:44389
     - API_TOKEN=""
    ports:
      - "5101:80"
    depends_on: 
        - db
        
  
  paymentmicroservice:
    image: ${DOCKER_REGISTRY-}paymentmicroservice
    build:
      context: .
      dockerfile: PaymentMicroservice/Dockerfile
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - DB_CONNECTION_STRING=Server=192.168.1.28,1432;Database=PaymentDB;User Id=sa;Password=Barisaltun508*;Trusted_Connection=False;MultipleActiveResultSets=true
    ports:
      - "44489:80"
    depends_on: 
        - db

  cashonledgerapi:
    image: ${DOCKER_REGISTRY-}cashonledgerapi
    build:
      context: .
      dockerfile: CashOnLedgerAPI/Dockerfile
    environment:
    - PAYMENT_URL=http://host.docker.internal:44489
    - API_TOKEN=""
    - ASPNETCORE_URL=http://+44389
    ports:
    - "44389:80"

  db:
     image: "mcr.microsoft.com/mssql/server:2019-latest"
     environment:
       SA_PASSWORD: "Barisaltun508*"
       ACCEPT_EULA: "Y"
       ports: "1432:1433"
       


